# Generated by Django 5.0.3 on 2024-06-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('bacherx', 'bacherx'), ('ayudante de cocina', 'Ayudantx de cocina'), ('cocinero', 'Cocinerx'), ('pastelerx', 'Pastelerx'), ('jefe de cocina', 'Jefx de cocina'), ('sommelier', 'Sommelier'), ('encargadx de sala', 'Encargado de sala'), ('chef ejecutivx', 'Chef ejecutivo'), ('Cajerx', 'Cajerx')], max_length=50)),
                ('currency', models.CharField(choices=[('usd', 'USD'), ('ars', 'ARS')], max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_type', models.CharField(choices=[('white', 'En blanco(Trabajo 100% registrado)'), ('black', 'En negro(Trabajo sin registrar)'), ('miti-miti', 'miti-miti(Media jornada de trabajo registrado, la otra media jornada sin registrar)')], max_length=10)),
                ('restaurant_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10)),
            ],
        ),
    ]
