# Generated by Django 5.0.3 on 2024-06-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='contract_type',
            field=models.CharField(choices=[('100% en blanco', 'En blanco(Trabajo 100% registrado)'), ('100% en negro', 'En negro(Trabajo sin registrar)'), ('Media jornada registrada - Media jornada sin registrar', 'Miti-Miti(Media jornada de trabajo registrado, la otra media jornada sin registrar)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='position',
            field=models.CharField(choices=[('Bacherx', 'bacherx'), ('Ayudantx de cocina', 'Ayudantx de cocina'), ('CocinerX', 'Cocinerx'), ('Pastelerx', 'Pastelerx'), ('Jefx de cocina', 'Jefx de cocina'), ('Sommelier', 'Sommelier'), ('Encargadx de sala', 'Encargado de sala'), ('Chef ejecutivx', 'Chef ejecutivo'), ('Cajerx', 'Cajerx')], max_length=50),
        ),
    ]
