# Generated by Django 5.0.3 on 2024-07-01 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdata', '0002_alter_jobdata_contract_type_alter_jobdata_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='contract_type',
            field=models.CharField(choices=[('100% en blanco', 'En blanco(Trabajo 100% registrado)'), ('100% en negro', 'En negro(Trabajo sin registrar)'), ('Media jornada registrada / Media jornada sin registrar', 'Media jornada de trabajo registrado, la otra media jornada sin registrar)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], max_length=3),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='position',
            field=models.CharField(choices=[('Bacherx', 'Bacherx'), ('Ayudantx de cocina', 'Ayudantx de cocina'), ('Cocinerx', 'Cocinerx'), ('Pastelerx', 'Pastelerx'), ('Jefx de pastelería', 'Jefx de pastelería'), ('Jefx de cocina', 'Jefx de cocina'), ('Sommelier', 'Sommelier'), ('Camarerx', 'Camarerx'), ('Encargadx de sala', 'Encargado de sala'), ('Chef ejecutivx', 'Chef ejecutivo'), ('Cajerx', 'Cajerx')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdata',
            name='salary',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
