# Generated by Django 5.0.3 on 2024-07-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdata', '0003_alter_jobdata_contract_type_alter_jobdata_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='contract_type',
            field=models.CharField(choices=[('100% en blanco', 'En blanco(Trabajo 100% registrado)'), ('100% en negro', 'En negro(Trabajo sin registrar)'), ('Media jornada registrada / Media jornada sin registrar', 'Media jornada de trabajo registrado, la otra media jornada sin registrar')], max_length=100),
        ),
    ]
